const mongoose = require('mongoose');

const partnerSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true, // The user associated with the partner
  },
  referralCode: {
    type: String,
    unique: true,
    required: true, // Unique referral code for the partner
  },
  totalRevenue: {
    type: Number,
    default: 0, // Total revenue generated by the partner's referrals
  },
  downloads: {
    type: Number,
    default: 0, // Number of downloads generated from the partner's referral
  },
  // other partner fields (e.g., payment details)
});

module.exports = mongoose.model('Partner', partnerSchema);
